### PR TITLE
Fixed load from saved state

### LINKED ISSUE #9: Loading from state conflicts between client and server side
When trying to load from a previous state there are differences caused by the server not having access to window.localstorage causing out of sync warnings visible on dev.

### PR DESCRIPTION
**Pull request by ruisilva450**
fixes #9

### CODE REVIEW

File: pages/index.js [hunk 1]
```diff
@@ -14,41 +14,43 @@ const generateWords = (words) => {
...
+  return localStorageValue != null ? localStorageValue : defaultValue;
+};
 
-  React.useEffect(() => {
-    if (typeof window !== "undefined") {
-      localStorage.setItem(localStorageKey, JSON.stringify(value));
-    }
-  }, [value instanceof Array ? value.length : value]);
+const Index = () => {
+  const [isLoading, setIsLoading] = React.useState(true);
```
Comment (CiprianoFreitas) [inline pages/index.js:23]: You can just import `useState` from react and the code will be less verbose. Simply
`const [isLoading, setIsLoading] = useState(true);`
